### ISSUE TITLE
Wrong path to tmp files.

### ISSUE THREAD

**Issue by macchrister** [bruienne/autonbi#10]
Running on macOS 10.13.4 and using "Install macOS HighSierra.app" version 10.13.4

bash-3.2# ./AutoNBI.py -s /Applications/Install\ macOS\ High\ Sierra.app/ -d /Files/build_nbi/ -n HighSierra-10.13.4-auto --auto
Locating installer...
Install source is /Applications/Install macOS High Sierra.app/Contents/SharedSupport/InstallESD.dmg
Mounting /Applications/Install macOS High Sierra.app/Contents/SharedSupport/InstallESD.dmg
Prepping /Files/build_nbi/ with source mounted at /private/tmp/tmpjjpkju/dmg.EWsxJB
Creating NBI at /Files/build_nbi/
Base NBI Operating System is 10.13.4
This is a 10.13 or newer installer, sourcing BaseSystem.dmg from SharedSupport.
NBI mounted at /private/tmp/tmpjjpkju/dmg.kdgxGw
Install source is 10.13 or newer, BaseSystem.dmg is in an alternate location...
Running self.dmgresize...
Will resize DMG at mount: /private/tmp/tmpjjpkju/dmg.kdgxGw/Install macOS High Sierra.app/Contents/SharedSupport/BaseSystem.dmg
Error "hdiutil: resize: failed. No such file or directory (2)
" while running command ['/usr/bin/hdiutil', 'resize', '-size', '8G', '-shadow', '/tmp/tmpjjpkju/BaseSystem.shadow', '/private/tmp/tmpjjpkju/dmg.kdgxGw/Install macOS High Sierra.app/Contents/SharedSupport/BaseSystem.dmg']
Running self.dmgattach...
Error "hdiutil: attach failed - No such file or directory
" while running command ['/usr/bin/hdiutil', 'attach', '-shadow', '/tmp/tmpjjpkju/BaseSystem.shadow', '-mountRandom', '/tmp/tmpjjpkju', '-nobrowse', '-plist', '-owners', 'on', '/private/tmp/tmpjjpkju/dmg.kdgxGw/Install macOS High Sierra.app/Contents/SharedSupport/BaseSystem.dmg']
Traceback (most recent call last):
  File "./AutoNBI.py", line 1364, in <module>
    main()
  File "./AutoNBI.py", line 1343, in main
    nbi.modify(nbimount, netinstallpath, nbishadow, mount)
  File "./AutoNBI.py", line 863, in modify
    basesystemplist = plistlib.readPlistFromString(plist)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 103, in readPlistFromString
    return readPlist(StringIO(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by poshpaws** [comment]
I also see this issue with the hs branch

**Comment by Cpt-Pessimist** [comment]
Remove the trailing '/' in your source path. 
Ex: `./AutoNBI.py -s /Applications/Install\ macOS\ High\ Sierra.app -d /Files/build_nbi/ -n HighSierra-10.13.4-auto --auto`
